# Generated by Django 5.2.5 on 2025-08-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
