# Generated by Django 5.2.5 on 2025-08-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0007_alter_employee_user'),
        ('task', '0003_employeetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingOffboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task_name', models.CharField(max_length=255)),
                ('applies_to_all', models.BooleanField(default=False)),
                ('task_type', models.CharField(blank=True, choices=[(1, 'onboarding'), (2, 'offboarding')], null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_task', to='employee_module.department')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='employee_module.jobtitle')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplyee_task', to='employee_module.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EmployeeTask',
        ),
    ]
