# Generated by Django 5.2.5 on 2025-08-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0002_alter_employeehistory_previous_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='employee/profile/profile_photo'),
        ),
    ]
