# Generated by Django 5.2.5 on 2025-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0003_alter_employeeprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hr'), (2, 'other')], default=1),
        ),
    ]
