# Generated by Django 5.2.5 on 2025-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0005_alter_emergencycontact_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hr'), (2, 'manager'), (3, 'other')], default=3),
        ),
    ]
